language: minimal
branches:
  only:
    - master

before_deploy: 
  - pip install --user awscli
  - ./file://config/set-aws.sh

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: test.nationalarchives.gov.uk
    region: eu-west-2
    skip_cleanup: true
    local-dir: deploy
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always
        on_success: always
after_deploy:
   - aws s3api put-bucket-website --bucket www.fullofwishes.co.uk --website-configuration file://config/routing-rules.json
   - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
