language: minimal
branches:
  only:
    - master
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: test.nationalarchives.gov.uk
    region: eu-west-2
    skip_cleanup: true
    local-dir: deploy
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always